name: Run tests

# Trigger the workflow on PRs
on:
    pull_request

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build with dotnet
      working-directory: ./src
      run: dotnet build
